name: Code check

on:
  push:
    branches: [ main ]

jobs:
  my-testing:



    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Проверить версию Python
        run: python --version



      - name: Запустить мою программу
        run: python myprog.py